# Generated by Django 5.2.15 on 2026-06-14 05:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetterVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('target_role', models.CharField(blank=True, max_length=120)),
                ('file', models.FileField(blank=True, upload_to='cover_letters/')),
                ('external_file_path', models.CharField(blank=True, help_text='Optional path to a file in COVER_LETTER_FOLDER.', max_length=800)),
                ('key_message', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('target_role', models.CharField(choices=[('data_engineering', 'Data Engineering'), ('data_science', 'Data Science'), ('quant_modelling', 'Quant / Modelling'), ('energy_analyst', 'Energy Analyst'), ('environmental_consulting', 'Environmental Consulting'), ('digital_consulting', 'Digital Consulting'), ('other', 'Other')], default='data_engineering', max_length=80)),
                ('file', models.FileField(blank=True, upload_to='resumes/')),
                ('external_file_path', models.CharField(blank=True, help_text='Optional path to a file in RESUME_FOLDER.', max_length=800)),
                ('skill_summary', models.TextField(blank=True)),
                ('experience_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted')], default='saved', max_length=40)),
                ('has_reply', models.BooleanField(default=False)),
                ('reply_date', models.DateField(blank=True, null=True)),
                ('current_stage', models.CharField(blank=True, max_length=160)),
                ('next_action', models.CharField(blank=True, max_length=250)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('cv_skill_summary', models.TextField(blank=True)),
                ('cv_experience_summary', models.TextField(blank=True)),
                ('match_notes', models.TextField(blank=True, help_text='JD vs CV fit, gaps, tailored story.')),
                ('notes', models.TextField(blank=True)),
                ('cover_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.coverletterversion')),
            ],
            options={
                'ordering': ['-date_applied', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_type', models.CharField(blank=True, help_text='HR screen, technical, hiring manager, final, etc.', max_length=120)),
                ('interviewers', models.CharField(blank=True, max_length=250)),
                ('questions_asked', models.TextField(blank=True)),
                ('performance_notes', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=40)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
            options={
                'ordering': ['application', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('role_type', models.CharField(choices=[('data_engineering', 'Data Engineering'), ('data_analytics', 'Data Analytics'), ('data_science', 'Data Science'), ('quant_modelling', 'Quant / Modelling'), ('energy', 'Energy'), ('environmental', 'Environmental'), ('digital', 'Digital'), ('other', 'Other')], default='data_engineering', max_length=80)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('work_type', models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('salary_range', models.CharField(blank=True, max_length=120)),
                ('job_url', models.URLField(blank=True)),
                ('platform', models.CharField(blank=True, help_text='LinkedIn, Seek, Indeed, company website, recruiter, etc.', max_length=100)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('date_saved', models.DateField(default=django.utils.timezone.localdate)),
                ('jd_text', models.TextField(blank=True)),
                ('jd_skill_summary', models.TextField(blank=True)),
                ('jd_experience_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='applications.company')),
            ],
            options={
                'ordering': ['-date_saved', 'company__name', 'title'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.jobposting'),
        ),
        migrations.CreateModel(
            name='OutcomeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_at_stage', models.CharField(choices=[('screening', 'Screening'), ('first_interview', 'First Interview'), ('technical', 'Technical Interview'), ('hiring_manager', 'Hiring Manager'), ('final', 'Final Round'), ('offer_negotiation', 'Offer Negotiation'), ('unknown', 'Unknown')], default='unknown', max_length=80)),
                ('reason_given', models.TextField(blank=True)),
                ('my_diagnosis', models.TextField(blank=True)),
                ('skill_gap', models.TextField(blank=True)),
                ('communication_gap', models.TextField(blank=True)),
                ('cv_issue', models.TextField(blank=True)),
                ('cover_letter_issue', models.TextField(blank=True)),
                ('salary_or_location_issue', models.TextField(blank=True)),
                ('action_for_next_application', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_review', to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.resumeversion'),
        ),
    ]
